# Positions
POS_CENTER = "CENTER"
POS_LEFT = "LEFT"
POS_RIGHT = "RIGHT"
POS_UP = 'UP'
POS_DOWN = 'DOWN'
#
# Keys
ARROW_UP = 'ARROW_UP'
ARROW_DOWN = 'ARROW_DOWN'
ARROW_LEFT = 'ARROW_LEFT'
ARROW_RIGHT = 'ARROW_RIGHT'
INSERT = 'INSERT'
DELETE = 'DELETE'
HOME = 'HOME'
END = 'END'
PAGE_UP = 'PAGE_UP'
PAGE_DOWN = 'PAGE_DOWN'
TAB = 'TAB'
RETURN = 'RETURN'
ESCAPE = 'ESCAPE'
# Textfield types
TF_ONELINE = 'TF_ONELINE'
TF_TYPES = [TF_ONELINE]
